Repository calblueprint/alemany, pull requests merged in 2021-12, with the labels that each got.

#50 [Phone Formatting] Allowed for different inputs
  package.json
  src/screens/LoginScreen.tsx
Labels: requires review

#54 Base Text Components
  App.tsx
  package.json
  src/hooks/useTheme.tsx
Labels: requires changes

#55 Colors constant
  src/hooks/useTheme.tsx
Labels: requires changes

#60 Add support for staying logged with phone auth & basic logout functionality
  package.json
  src/components/ViewContainer.tsx
  src/navigation/TabNavigator.tsx
  src/navigation/index.tsx
  src/screens/AuthLoadingScreen.tsx
  src/screens/LoginScreen.tsx
  src/screens/VerificationScreen.tsx
  types.tsx
Labels: approved

#62 Only allow admin-authorized phone numbers to create accounts
  src/database/firebase.tsx
  src/screens/LoginScreen.tsx
Labels: approved

#59 Update react-native-paper version and deprecate Prop Types
  .eslintrc.json
  package.json
  src/screens/NotFoundScreen.tsx
  src/screens/SearchScreen.tsx
  src/screens/TreeDetailsScreen.tsx
  src/screens/TreeScreen.tsx
  src/screens/VerificationScreen.tsx
  types.tsx
Labels: help wanted
